library(readxl)
DF <- read_excel("C:/Users/Nick Vietri/Desktop/dataset1.xls")
View(DF)

if(!require("tidyverse"))
  install.packages("tidyverse")

library(readxl)
df <- read_excel("C:/Users/Nick Vietri/Desktop/dataset1.xls")
View(df)

count(df,df$Title)
df$Title <- replace(df$Title, df$Title == "Aldermen","Alderman")
df$Title <- replace(df$Title, df$Title == "Clerk","Clery of Court")
df$Title <- replace(df$Title, df$Title == "Constable(s)", "Constable")
df$Title <- replace(df$Title, df$Title == "Council Member at Large", "Council Member")
df$Title <- replace(df$Title, df$Title == "Council Member I", "Council Member")
df$Title <- replace(df$Title, df$Title == "Council Member II", "Council Member")
df$Title <- replace(df$Title, df$Title == "Council Member III", "Council Member")
df$Title <- replace(df$Title, df$Title == "Council Member(S)", "Council Member")
df$Title <- replace(df$Title, df$Title == "Councilman", "Council Member")
df$Title <- replace(df$Title, df$Title == "Councilman at Large", "Council Member")
df$Title <- replace(df$Title, df$Title == "Councilmember", "Council Member")
df$Title <- replace(df$Title, df$Title == "Councilmen", "Council Member")
df$Title <- replace(df$Title, df$Title == "Judge, Court of Appeals", "Judge")
df$Title <- replace(df$Title, df$Title == "Judge, Family Court", "Judge")
df$Title <- replace(df$Title, df$Title == "Associate Justice", "Judge")
df$Title <- replace(df$Title, df$Title == "City Judge", "Judge")
df$Title <- replace(df$Title, df$Title == "City Judge, City Court", "Judge")
#-5 missing replace commands, -5 count command after replace 90/100